---
# See https://docs.ansible.com/projects/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: microsoft
name: wsl
version: 0.1.0
readme: README.md
authors:
  - Ansible Eco Content Team (github.com/eco-ansible-content)
description: A collection enabling the management of Windows Subsystem for Linux (WSL) using Ansible.
license_file: LICENSE
tags:
  - microsoft
  - wsl
  - windows
repository: https://github.com/ansible-collections/microsoft.wsl
documentation: https://github.com/ansible-collection-migration/microsoft.wsl/tree/main/README.md
homepage: https://github.com/ansible-collections/microsoft.wsl
issues: https://github.com/ansible-collections/microsoft.wsl/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - tests/integration/inventory.winrm
  # AI
  - claude/
  - .lola/
  - CLAUDE.md
